name: Deploy OWASP Rules to Splunk

on:
  push:
    paths:
      - '**/detections/**/*.yml' # Запуск при любом изменении yml файлов в папках detections
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run deployment script
        env:
          SPLUNK_HOST: ${{ secrets.SPLUNK_HOST }}
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        # ИСПРАВЛЕНИЕ ЗДЕСЬ: прямой путь к скрипту, так как он лежит в корне репозитория в папке scripts
        run: python scripts/deploy_rules.py
